### ISSUE TITLE
Warnings During Run / Tests

### ISSUE THREAD

**Issue by zoffixznet** [teodozjan/pod6-coverage#13]
Getting `What is Grepper ? ` warnings during run and saw them during tests during module installation too.
```bash
zoffix@ZofMain:~/.panda-work/1447717388_1$ pod-coverage 
What is Grepper ?  in method parse at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/lib/Pod/Coverage.pm6:184
What is Grepper ?  in method parse at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/lib/Pod/Coverage.pm6:184
Test::Coverage has pod
Pod::Coverage has pod
Pod::To::Keywords has pod
zoffix@ZofMain:~/.panda-work/1447717388_1$ 
```

**Comment by teodozjan** [comment]
I need to check what is that :)

https://github.com/rakudo/rakudo/blob/8e19973b5b4f73a50e76dc6187a27108f7174bd8/src/core/Any-iterable-methods.pm

**Comment by teodozjan** [comment]
Also we have another warning to work out. More obvious even `Could not open lib/Pod/Coverage.pod. Failed to stat file: no such file or directory`
