### ISSUE TITLE
Endless loop of t/selftest.t

### ISSUE THREAD

**Issue by niner** [teodozjan/pod6-coverage#20]
When trying to install on current rakudo, the tests run into an endless recursion. Attaching a backtrace:

[backtrace.txt](https://github.com/teodozjan/pod6-coverage/files/48506/backtrace.txt)

**Comment by teodozjan** [comment]
I'm not sure what changed. I need to add debug symbols to traverser
https://travis-ci.org/teodozjan/pod6-coverage/builds/92923618

**Comment by sylvarant** [comment]
I have similar issues ever since upgrading perl6

**Comment by teodozjan** [comment]
The problem lies in https://github.com/teodozjan/pod6-coverage/blob/master/lib/Pod/Coverage/Full.pm6#L146

```
for $whoO.WHO<EXPORT>.WHO<ALL>.WHO.values -> $val 
```

Contains alos imported modules. In this case JSON and everything  goes into indefinite recurstion. I can add double check protection but I'm afraid this hacky solution is wrong.

**Comment by teodozjan** [comment]
https://github.com/teodozjan/pod6-coverage/commit/0c28383ba56aee8a7903346fae6f3ca2cce800a7

**Comment by teodozjan** [comment]
Perl6 is under heavy development now. Everyday I have different error so this defect has to wait until Christmas

**Comment by teodozjan** [comment]
There is no longer infinite loop
